### PR TITLE
added code-along cells and content

### PR DESCRIPTION
**Pull request by Cheffrey2000**

### CODE REVIEW

**Comment by ismayc** [comment]
@Cheffrey2000 I think we want this PR to go into `curriculum` instead of `master` and then we will run the splitter?

**Comment by ismayc** [comment]
Might be worth reminding students that things like `dict_keys[['meta', 'data']]` are the solution they are looking to get? Potentially having that in a different cell might make it easier to note that. I can't remember if the style you've done here is common throughout the Curriculum though? If so, no change needed.

**Comment by ismayc** [comment]
Since the solutions aren't provided for the four chunks before *Extracting a Value from a JSON File*, I'd add that note in to make sure students are aware of that.


Otherwise, this looks good! Let's keep thinking about more ways to have students do these kinds of things throughout.

**Review by ismayc — CHANGES_REQUESTED** [review]
Added in my requested changes in comments. Let me know if clarity is needed in my feedback.

**Comment by Cheffrey2000** [comment]
@ismayc Can you take another look and let me know if i addressed all of the issues you saw.  Thanks.

**Review by christine-egan42 — APPROVED** [review]

**Comment by christine-egan42** [comment]
@Cheffrey2000 -- the code-along cells here looks great. I am unsure how to address the additional changes the @ismayc is requesting using the branch splitter.

**Comment by ismayc** [comment]
Apologies! I didn't get the notification that you had tagged me here, but I was notified of the merge :-/. I'm happy to review this again if you'd like?

**Pull request merged**
